stages:
  - build
  - pusher-dev
  - update_portainer-development
  - update_portainer-qa

master_build:
  stage: build
  tags:
    #- 'recruitment'
    - 'runner-60-1-13'
  variables:
    REGISTRY_ADDRESS: 'registry.cebu.dnadev.net'
    REGISTRY_USERNAME: 'dna'
    REGISTRY_PASSWORD: '3QFh6zZ2u2fnHbnt3pwy'
  script:
    - 'docker login $REGISTRY_ADDRESS -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD'
    - "docker build -t $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID -f dockerfile \
      --build-arg PROJECT=$CI_PROJECT_NAME ."
    - 'docker tag $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME'
    - 'docker push $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID'
    - 'docker push $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME'
  only:
    - 'development'

# pusher_dev:
#   stage: pusher-dev
#   variables:
#     REGISTRY_ADDRESS: 'registry.cebu.dnadev.net'
#     REGISTRY_USERNAME: 'dna'
#     REGISTRY_PASSWORD: '3QFh6zZ2u2fnHbnt3pwy'
#     SUDO_PASSWORD: "DNAG0ds!!"
#     STACK_ID: 6
#     PORTAINER_DATA: '/mnt/sdb1/docker/volumes/portainer-data/_data/compose'
#     #'/var/lib/docker/volumes/portainer_data/_data/compose/'
#   script:
#     - 'docker login $REGISTRY_ADDRESS -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD'
#     - 'docker pull $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID'
#     - 'docker pull $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME'
#     # - 'ls $PORTAINER_DATA/$STACK_ID'
#     # - 'cat $PORTAINER_DATA/$STACK_ID/docker-compose.yml'
#     # - 'docker restart recruitment-recruitment-portal-1'
#     # - 'docker restart recruitment-recruitment-portal-2'
#     # - 'docker restart recruitment-recruitment-portal-3'
#     # - 'docker restart recruitment-recruitment-portal-4'
#   only:
#     - 'development'
#   tags:
#      #- 'recruitment'
#     - 'runner-60-1-13'

update_stack:
  stage: update_portainer-development
  tags:
     #- 'recruitment'
    - 'runner-60-1-13'
  variables:
    ENDPOINT_ID: 2
    STACK_ID: 16
    PORTAINER_USERNAME: 'ci'
    PORTAINER_PASSWORD: 'hcb2VfQ8SgM9QMWWJo9n'
    PORTAINER_HOST: https://portainer.cebu.dnadev.net
    PORTAINER_YML_FILE: recruitment.yml
    REGISTRY_ADDRESS: 'registry.cebu.dnadev.net'
    FILE_PATH: /var/apps/portainer
  script:
    - PORTAINER_HOST=$PORTAINER_HOST portainer login -u $PORTAINER_USERNAME -p $PORTAINER_PASSWORD
    - touch $FILE_PATH/$PORTAINER_YML_FILE
    - rm -rf  $FILE_PATH/$PORTAINER_YML_FILE && PORTAINER_HOST=$PORTAINER_HOST portainer stackfile $STACK_ID $FILE_PATH/$PORTAINER_YML_FILE
    - sed -i "s/${CI_PROJECT_NAME}:.*/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}/g" $FILE_PATH/$PORTAINER_YML_FILE
    - echo 'updating recruitment-portal'
    - PORTAINER_HOST=$PORTAINER_HOST portainer stack:update  $ENDPOINT_ID  $STACK_ID  $FILE_PATH/$PORTAINER_YML_FILE
  only:
    - 'development'

update_stack_qa:
  stage: update_portainer-qa
  tags:
    - 'qa'
  variables:
    ENDPOINT_ID: 5
    STACK_ID: 20
    PORTAINER_USERNAME: 'ci'
    PORTAINER_PASSWORD: 'LmqfEfr5nDurvatgw8rv'
    PORTAINER_HOST: https://portainer.platform.dnadev.net
    PORTAINER_YML_FILE: recruitment.yml
    REGISTRY_ADDRESS: 'registry.cebu.dnadev.net'
    REGISTRY_USERNAME: 'dna'
    REGISTRY_PASSWORD: '3QFh6zZ2u2fnHbnt3pwy'
    BASE_REF_NAME: development
    FILE_PATH: /var/apps/portainer
  script:
    - docker login $REGISTRY_ADDRESS -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
    - docker pull $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$BASE_REF_NAME
    - docker tag $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$BASE_REF_NAME $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID
    - docker tag $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$BASE_REF_NAME $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker push $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID
    - docker push $REGISTRY_ADDRESS/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME

    - PORTAINER_HOST=$PORTAINER_HOST portainer login -u $PORTAINER_USERNAME -p $PORTAINER_PASSWORD
    - touch $FILE_PATH/$PORTAINER_YML_FILE
    - rm -rf  $FILE_PATH/$PORTAINER_YML_FILE && PORTAINER_HOST=$PORTAINER_HOST portainer stackfile $STACK_ID $FILE_PATH/$PORTAINER_YML_FILE
    - sed -i "s/${CI_PROJECT_NAME}:.*/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}/g" $FILE_PATH/$PORTAINER_YML_FILE
    - echo 'updating recruitment-portal'
    - PORTAINER_HOST=$PORTAINER_HOST portainer stack:update  $ENDPOINT_ID  $STACK_ID  $FILE_PATH/$PORTAINER_YML_FILE
  only:
    - 'qa'