services:
  redis:
    image: redis:alpine
    ports:
      - "6378:6379"
  recruitment-portal:
    image: registry.dnamicro.com/recruitment-portal:development
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    environment:
      DEBUG: false

      # Deployment
      NODE_ENV: production

      # Abort signal timeout
      OPERATION_TIMEOUT: 1000
      STORE_URL: http://172.18.51.11:5001
      REDIS_CACHE_ENDPOINT: 172.18.51.11
      REDIS_CACHE_PORT: 6378

      GOOGLE_PLACES_API_KEY: AIzaSyCNDmLeX_vZYnZolZSRMRZJSSuKLG3s2C8

    ports:
      - "3000:3000"
