export default [
  "contact",
  "organization",
  "user_role",
  "communication_template",
  "account_organization",
  "device",
  "location",
  'timeline',
  // Project Entities
  "device_remote_access_session",
  "device_configurations",
  "device_filter_rules",
  "device_nat_rules",
  "aliases",
  "versions",
  "device_tunnel",
  "device_tunnels",
  "device_ssh_sessions",
  "device_tty_sessions",
  "device_contact",
  "device_contacts",
  "devices",
  'system_resources',
];