export const currencies = {
  "US Dollar": "$",
  Euro: "€",
  "British Pound": "£",
  "Japanese Yen": "¥",
  "Chinese Yuan": "¥",
  "Indian Rupee": "₹",
  "Australian Dollar": "A$",
  "Canadian Dollar": "C$",
  "Swiss Franc": "CHF",
  "Mexican Peso": "$",
  "Brazilian Real": "R$",
  "South African Rand": "R",
  "Russian Ruble": "₽",
  "South Korean Won": "₩",
  "Indonesian Rupiah": "Rp",
  "Turkish Lira": "₺",
  "Saudi Riyal": "﷼",
  "Swedish Krona": "kr",
  "Norwegian Krone": "kr",
  "Danish Krone": "kr",
  "Thai Baht": "฿",
  "Singapore Dollar": "S$",
  "Malaysian Ringgit": "RM",
  "Hong Kong Dollar": "HK$",
  "New Zealand Dollar": "NZ$",
  "Philippine Peso": "₱",
  "Pakistani Rupee": "₨",
  "Bangladeshi Taka": "৳",
  "Egyptian Pound": "£",
  "Vietnamese Dong": "₫",
  "UAE Dirham": "د.إ",
  "Argentine Peso": "$",
  "Chilean Peso": "$",
  "Colombian Peso": "$",
  "Peruvian Sol": "S/",
  "Hungarian Forint": "Ft",
  "Polish Zloty": "zł",
  "Czech Koruna": "Kč",
  "Israeli Shekel": "₪",
  "Nigerian Naira": "₦",
  "Kenyan Shilling": "KSh",
  "Ghanaian Cedi": "₵",
  "Tanzanian Shilling": "TSh",
  "Ugandan Shilling": "USh",
  "Moroccan Dirham": "د.م.",
  "Tunisian Dinar": "د.ت",
  "Algerian Dinar": "د.ج",
  "Iraqi Dinar": "ع.د",
  "Jordanian Dinar": "د.ا",
  "Lebanese Pound": "ل.ل",
  "Syrian Pound": "£",
  "Omani Rial": "ر.ع.",
  "Qatari Riyal": "﷼",
  "Kuwaiti Dinar": "د.ك",
  "Bahraini Dinar": "ب.د",
  "Sri Lankan Rupee": "රු",
  "Nepalese Rupee": "रू",
  "Myanma Kyat": "K",
  "Cambodian Riel": "៛",
  "Laotian Kip": "₭",
  "Brunei Dollar": "B$",
  "Mauritian Rupee": "₨",
  "Maldivian Rufiyaa": "ރ",
  "Fijian Dollar": "FJ$",
  "Papua New Guinean Kina": "K",
  "Solomon Islands Dollar": "SI$",
  "Vanuatu Vatu": "VT",
  "Samoan Tala": "T",
  "Tongan Paʻanga": "T$",
  "CFP Franc": "₣",
  "Central African CFA Franc": "CFA",
  "West African CFA Franc": "CFA",
  "Cape Verdean Escudo": "$",
  "Comorian Franc": "CF",
  "Djiboutian Franc": "Fdj",
  "Eritrean Nakfa": "Nfk",
  "Ethiopian Birr": "Br",
  "Liberian Dollar": "L$",
  "Sierra Leonean Leone": "Le",
  "Somali Shilling": "Sh.So.",
  "Sudanese Pound": "SDG",
  "Zimbabwean Dollar": "Z$",
};
