import { type Locator, type Page } from '@playwright/test';

export class DeviceGridPage {
  readonly page: Page;
  readonly gridContainer: Locator;
  readonly createButton: Locator;
  readonly searchButton: Locator;
  readonly searchModalInput: Locator;
  readonly rows: Locator;
  readonly onlineBadges: Locator;
  readonly authCells: Locator;

  constructor(page: Page) {
    this.page = page;
    this.gridContainer = page.locator('[data-test-id="device-grid-table-body"]');
    this.createButton = page.locator('[data-test-id="device-grid-create-button"]');
    this.searchButton = page
      .locator('[data-test-id="device-grid-search-button"]')
      .first();
    this.searchModalInput = page
      .locator('[data-test-id="device-grid-search-input"]')
      .first();
    // Rows use the pattern generated by testIDFormatter: device-grid-table-body-row-{rowId}{index}
    this.rows = page.locator('[data-test-id^="device-grid-table-body-row"]');
    this.onlineBadges = page.locator('[data-test-id="device-online-badge"]');
    this.authCells = page.locator('[data-test-id="device-auth-cell"]');
  }

  async goto() {
    await this.page.goto('/portal/device/grid');
    await this.page.waitForLoadState('networkidle');
  }

  async getRowCount() {
    return this.rows.count();
  }

  async clickFirstRow() {
    await this.rows.first().click();
    await this.page.waitForLoadState('networkidle');
  }

  async openSearch() {
    await this.searchButton.click();
  }

  async searchInModal(query: string) {
    await this.openSearch();
    await this.searchModalInput.fill(query);
  }

  columnHeader(columnId: string): Locator {
    return this.page.locator(
      `[data-test-id="device-grid-table-head-row-${columnId}"]`,
    );
  }

  columnSortIndicator(columnId: string, direction: 'Asc' | 'Desc'): Locator {
    return this.page.locator(
      `[data-test-id="device-grid-table-head-row-${columnId}-sort-${direction.toLowerCase()}"]`,
    );
  }

  sortBadge(label: string, direction: 'Asc' | 'Desc'): Locator {
    return this.page
      .locator('[data-test-id="device-sort-by-badge"]')
      .filter({ hasText: `${label} (${direction})` });
  }

  async sortColumn(columnId: string, direction: 'Asc' | 'Desc'): Promise<void> {
    const header = this.columnHeader(columnId);
    await header.hover();
    await header.locator('button').click();
    const menuText =
      direction === 'Asc' ? 'Sort by Ascending' : 'Sort by Descending';
    await this.page.getByRole('menuitem', { name: menuText }).click();
  }

  async resetSort(): Promise<void> {
    const resetButton = this.page.locator('button[name="resetSortButton"]');
    if (await resetButton.isVisible()) {
      await resetButton.click();
      await this.page.waitForLoadState('networkidle');
    }
  }

  firstRowCell(testId: string): Locator {
    return this.rows.first().locator(`[data-test-id="${testId}"]`);
  }

  async getCellAttributeValues(
    testId: string,
    attr: string,
  ): Promise<string[]> {
    const cells = this.rows.locator(`[data-test-id="${testId}"]`);
    const count = await cells.count();
    const values: string[] = [];
    for (let i = 0; i < count; i++) {
      const value = await cells.nth(i).getAttribute(attr);
      if (value !== null) values.push(value);
    }
    return values;
  }

  groupBadge(label: string): Locator {
    return this.page
      .locator('[data-test-id="device-group-by-badge"]')
      .filter({ hasText: label });
  }

  get groupRows(): Locator {
    return this.page.locator(
      '[data-test-id^="device-grid-table-body-row-cell-grouping"]',
    );
  }

  get groupRowExpandCells(): Locator {
    return this.page
      .locator('tr')
      .filter({
        has: this.page.locator(
          '[data-test-id^="device-grid-table-body-row-cell-grouping"]',
        ),
      })
      .locator('[data-test-id^="device-grid-table-body-row-cell-expand"]');
  }

  get expandedDataRowCells(): Locator {
    // Child rows always have a 'group-by' column cell; parent group rows use 'grouping' instead.
    // This holds regardless of which column is grouped (even when grouping by 'code').
    return this.page.locator(
      '[data-test-id^="device-grid-table-body-row-cell-group-by"]',
    );
  }

  async expandFirstGroupRow(): Promise<void> {
    await this.groupRowExpandCells.first().click();
  }

  async groupColumn(columnId: string, label: string): Promise<void> {
    const header = this.columnHeader(columnId);
    await header.hover();
    await header.locator('button').click();
    await this.page
      .getByRole('menuitem', { name: `Group by "${label}"` })
      .click();
  }

  async resetGrouping(): Promise<void> {
    const removeBtns = this.page.locator(
      '[data-test-id="device-remove-grouping-button"]',
    );
    const count = await removeBtns.count();
    for (let i = 0; i < count; i++) {
      await removeBtns.first().click();
      await this.page.waitForLoadState('networkidle');
    }
  }
}
